### ISSUE TITLE
Integrate KDE's decoration protocol

### ISSUE THREAD

**Issue by vberger** [Smithay/client-toolkit#1]
An early version is available in wayland-protocols : https://docs.rs/wayland-protocols/0.20.1/wayland_protocols/misc/server_decoration/client/index.html

There is also ongoing discussion on the wayland mailling lists and some variant of the protocol is likely to be soon standardized : https://lists.freedesktop.org/archives/wayland-devel/2018-April/037933.html

The idea would be to make a `ServerFrame<F: Frame>` implementing `window::Frame` that would use the server decoration protocol if available and if not fallback to the `F` frame.

**Comment by vberger** [comment]
Actually, it should probably not be a `Frame` instance, but rather an other method on `Window` to create it with the server decoration protocol support, as it requires access to a new global.

**Comment by emersion** [comment]
The xdg-decoration protocol has been merged in wayland-protocols 1.15.

**Comment by vberger** [comment]
tentative implementation is up in #20, @emersion do you know of any compositor implementing `xdg-toplevel-v1` for testing this? Does rootson already support it by chance?

**Comment by emersion** [comment]
We have a working implementation in this PR: https://github.com/swaywm/wlroots/pull/1053

It's not yet merged because it requires a `wayland-protocols` update in the Arch repos (just bumped the maintainers though - hopefully we'll be able to merge soon).
