### ISSUE TITLE
ConceptFrame: handle Tiled states

### ISSUE THREAD

**Issue by vberger** [Smithay/client-toolkit#105]
Following 1c6ac4cbf9db6e9d713ad8a3b10ad162c29edaa7, the `Frame` now has access to the whole set of XDG states for the window. This includes the `Tiled*` states, which notify that the window is tiled on some of its sides.

The `ConceptFrame` should take this information into account, by unmapping the invisible subsurfaces for the associated tiled sides, so that it does not display resizing cursor hints on tiled sides.

**Comment by kchibisov** [comment]
We should include fullscreen here too.

**Comment by vberger** [comment]
Following #183, the decorations provided in SCTK are explicitly FallbackFrame, a minimalist set of decorations that ensure usability of the window but makes no attempt at particular visual quality. Users of SCTK are invited to create their own implementation of the Frame trait fitting their needs.
