### ISSUE TITLE
Examples freezes after TTY switch

### ISSUE THREAD

**Issue by kchibisov** [Smithay/client-toolkit#106]
Just do a TTY switch and try to resize a window, it should freeze and just update a border(at least on sway).

Works just fine on `v0.6.x`, so I'd assume a `v0.7.0` regression.

**Comment by vberger** [comment]
Indeed, this seriously looks like a deadlock.

**Comment by vberger** [comment]
Hmm, wait, could you tell me which example does this precisely? I only get a deadlock with `kbd_input`, and only after fixing an other bug first. Otherwise I cannot reproduce this.

**Comment by vberger** [comment]
I pushed a fix for the other bug on master. Can you check if your freeze is still present with it? And if so, give more details about how to repro?

**Comment by kchibisov** [comment]
Oh, I've tested `selection` and `kbd_intput` let me test your fix.

**Comment by kchibisov** [comment]
Seems to be fixed by  5668aaf
