### ISSUE TITLE
Decide what to do about memmap

### ISSUE THREAD

**Issue by vberger** [Smithay/client-toolkit#112]
The `memmap` crate, that SCTK currently uses for memory-mapping in the SHM helpers (`MemPool` and `DoubleMemPool`) seems to be unmaintained. It has not received a single commit in 2 years, and has [several reported issues](https://github.com/danburkert/memmap-rs/issues).

We probably need to consider choosing an other one.

**Comment by Matthias-Fauconneau** [comment]
Not a big concern but I think https://github.com/RazrFalcon/memmap2-rs would be the obvious replacement.

**Comment by vberger** [comment]
Closing in favor of #165
