### ISSUE TITLE
Map keyboard

### ISSUE THREAD

**Issue by Matthias-Fauconneau** [Smithay/client-toolkit#119]
I find the map_keyboard_with_repeat API a bit too high level for a toolkit.
If possible I think it would be nicer to let the users (higher level frameworks?) explicitly setup what's needed.
That would require to show the xkb layout keycode->keysym mapper.

P.S: Users of calloop key repeat helper are probably looking for that higher level anyway so the
glued together combined map/unfold over the keyboard input callback should be fine for that case.

**Comment by vberger** [comment]
I'm sorry, but I don't really understand what you want here. What kind of control over the setup would you need precisely?

**Comment by Matthias-Fauconneau** [comment]
I only need xkb translation.
I can get that now but it's a bit weird to also have to add code to
ignore the repeat feature.
Without repeat, I don't see any value in map wrapping the callback, so
I'd interface the underlying "libxkbcommon-rs".

**Comment by vberger** [comment]
Note that with SCTK 0.9, there is now `map_keyboard` which only does keymap translation, and `map_keyboard_repeat` that also handles repetition, so if you don't care about key repetition you can use the former.

Now apart from that, SCTK's keyboard helper is meant for users that just want to not have to worry about managing xkbcommon and get their keyboard events interpreted easily.

If you want some specific keymap handling, nothing prevents you from using libxkbcommon directly, there are several rust crates binding it already existing.

I'm sorry but don't understand what SCTK could provide that would be between the current `map_keyboard` and just letting the user implement the keyboard themselves and handle xkbcommon...
