### ISSUE TITLE
Why does create_surface/setup_surface do surface.detach?

### ISSUE THREAD

**Issue by myfreeweb** [Smithay/client-toolkit#132]
This causes `thread 'main' panicked at 'Attemping to create an object from a non-attached proxy.'` when trying to get a frame callback from a sctk-created surface.

I guess I should've realized that it's not `Main` but I was completely baffled by this error, wondering what the hell is going on with my frame callback for quite some time >_<

**Comment by vberger** [comment]
Oh indeed. The detach is done to avoid handing out a `Main<_>`, so that the user don't attempt to assign a new filter to the object. But at the time it looks like I didn't have frame callbacks in mind. These functions could absolutely return an `Attached<WlSurface>` instead!

**Comment by kchibisov** [comment]
You're still free to do something like, right?

```rust
let surface: Proxy<wl_surface::WlSurface> = env.create_surface().into();
let surface = surface.attach(queue.token());
```

**Comment by myfreeweb** [comment]
> You're still free to do something like

Sure, but that requires also passing the `queue` around (so far haven't needed it anywhere after initial event loop setup), which is a bit annoying.
