### ISSUE TITLE
Innability to toggle between ServerSide and None decorations.

### ISSUE THREAD

**Issue by kchibisov** [Smithay/client-toolkit#143]
If you try to do so, you'll get protocol error.

`zxdg_decoration_manager_v1@7: error 0: xdg_toplevel_decoration must not have a buffer at creation`.

My use case is to hide client side decorations for fullscreen windows, however since there's no way to get current decorations status, as well as hide draw hidden client side decorations, I have to do toggle between `FollowServer` and `None`, which doesn't work due to the mentioned protocol violation.

**Comment by vberger** [comment]
Indeed, we currently are hitting the issue as `xdg_toplevel_decoration` must be initialized at the start. This might change in the future, but for now we need to deal with it.

Once the `xdg_toplevel_decoration` object exists, there are two ways to disable server-side decorations:

- request client-side decorations, but this may be refused by the server
- release the `xdg_toplevel_decoration` object, but this is definitive

Assuming clients that which to switch between "server-side" and "client-side" are nonexistent, and that the only relevant switches are either "SSD from/to undecorated" and "CSD from/to undecorated", we could implement the following logic:

- at start, the `xdg_toplevel_decoration` is created if available, in `FollowServer` mode (like now)
- if `ClientSide` is requested, the `xdg_toplevel_decoration` is dropped
- if `None` is requested, if the `xdg_toplevel_decoration` is alive, send `request(clientside)`, and in both case hide the `Frame`
- if `ServerSide` or `FollowServer` is requested, if the `xdg_toplevel_decoration` is alive, send the appropriate request, if not, do as if `ClientSide` was requested

The general idea is thus that once `ClientSide` has been requested once, all SSD options are no longer available, and all options behave as if the compositor did not support `xdg-decoration`, by fallbacking to CSD.

When switching between SSD and `None` we still have the risk of the server refusing to remove the SSD, but at this point we cannot do much more...
