### ISSUE TITLE
Transparent window icons overlap multiple shapes incorrectly

### ISSUE THREAD

**Issue by chrisduerr** [Smithay/client-toolkit#161]
When using semi-transparent window icons, there are some areas of increased intensity where different parts of the icons overlap. This seems like the usual problem you get when just rendering things to the target buffer immediately with the target transparency, instead of merging the shapes without any opacity before rendering it all together with the correct one.

Since one image speaks a thousand words:

![tmp](https://user-images.githubusercontent.com/8886672/95245010-07474480-0802-11eb-9e25-6d5abcdfa591.png)

**Comment by vberger** [comment]
Indeed, I guess our drawing code is too naive here, thanks for reporting it!

**Comment by vberger** [comment]
Following #183, the decorations provided in SCTK are explicitly `FallbackFrame`, a minimalist set of decorations that ensure usability of the window but makes no attempt at particular visual quality. Users of SCTK are invited to create their own implementation of the Frame trait fitting their needs.

**Comment by chrisduerr** [comment]
> Users of SCTK are invited to create their own implementation of the Frame trait fitting their needs.

Without having to look into this myself, this should make it trivial to provide external crates that plug into SCTK which provide whatever frame you might want to, right? So in theory this could work like a compile-time plugin system for SCTK frames? Or is there anything in this trait that would make it complicated to implement it in a separate crate?

**Comment by vberger** [comment]
The trait (and the rest of the interface of SCTK) is meant to be implementable externally, so yes, a crate providing an implementation for this trait should be possible without difficulty. If not, I'll consider it a bug in SCTK to be fixed.
