### ISSUE TITLE
Draw shadows or borders around concept frame decorations

### ISSUE THREAD

**Issue by kchibisov** [Smithay/client-toolkit#162]
Having 2 sctk windows one over another could become challenging identify the where one window ends and other starts, since there's neither border nor shadows. GTK users shadows for such thing for example.

It's very noticeable with alacritty , which window is just one solid colored rectangle.

![picture](https://user-images.githubusercontent.com/27620401/98502562-59e1a980-2263-11eb-8cd3-7804fb7972c2.png)

**Comment by myfreeweb** [comment]
Looks like subsurfaces with buffers are currently allocated for the border, even though nothing is drawn there. (These helped uncover [a fun bug in Wayfire](https://github.com/WayfireWM/wayfire/issues/865), hehe.)

When shadows/borders are implemented, if the application is able to turn them off: the subsurfaces should not be created if they won't be drawn and only the title bar will be.

Ideally they should be deallocated when fullscreened too?

https://github.com/Smithay/client-toolkit/blob/0bbda781acc40798b31cd2b08a454b432ecf6e85/src/window/concept_frame.rs#L548

(btw, I hope "fullscreened" here includes "tiled")

**Comment by kchibisov** [comment]
@myfreeweb subsurfaces are not presented when you do `set_hidden` on the window  https://github.com/Smithay/client-toolkit/blob/0bbda781acc40798b31cd2b08a454b432ecf6e85/src/window/concept_frame.rs#L513

**Comment by myfreeweb** [comment]
No, I mean, not when everything is hidden, but when **the title bar is drawn** but not the borders.

**Comment by kchibisov** [comment]
Yeah, I think they should be removed entire for fullscreen and other states properly as well, will require some refactoring.

**Comment by kchibisov** [comment]
@myfreeweb the issue you're talking about is https://github.com/Smithay/client-toolkit/issues/105

**Comment by vberger** [comment]
@myfreeweb these transparent subsurfaces are necessary and need to exist, as they serve to receive pointer input to allow the user to start an interactive resize of the window, so we need to draw them even if their content is empty (unless the window is tiled, as @kchibisov noted).

**Comment by vberger** [comment]
Following #183, the decorations provided in SCTK are explicitly `FallbackFrame`, a minimalist set of decorations that ensure usability of the window but makes no attempt at particular visual quality. Users of SCTK are invited to create their own implementation of the `Frame` trait fitting their needs.
