### ISSUE TITLE
Titlebar color do not respect GNOME dark theme

### ISSUE THREAD

**Issue by akhilman** [Smithay/client-toolkit#164]
Window titlebar is always bright, even when the GNOME/GTK theme is dark and `gtk-application-prefer-dark-theme` is set to `1`.

![image](https://user-images.githubusercontent.com/180812/99893152-21a08900-2caf-11eb-8ab5-08a0e39728e9.png)

**Comment by vberger** [comment]
Well, SCTK is not a Gnome nor GTK app, so indeed, it does not read GTK-specific configuration files.

The decorations API exposes a way for apps to have full control of the color scheme of the Concept Frame, via [`Window::set_frame_config`](https://docs.rs/smithay-client-toolkit/0.12.0/smithay_client_toolkit/window/struct.Window.html#method.set_frame_config),iit is up to them to use that if they wish to follow GTK's configuration.
