### ISSUE TITLE
 RUSTSEC-2020-0077: memmap is unmaintained

### ISSUE THREAD

**Issue by brightly-salty** [Smithay/client-toolkit#165]
After running `cargo audit` on my project, which has a transient dependence on smithay-client-toolkit, I got the following security advisory concerning the `memmap` dependency:
```
Crate:         memmap
Version:       0.7.0
Warning:       unmaintained
Title:         memmap is unmaintained
Date:          2020-12-02
ID:            RUSTSEC-2020-0077
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0077
Dependency tree:
memmap 0.7.0
└── smithay-client-toolkit 0.12.0
```
From the [website](https://rustsec.org/advisories/RUSTSEC-2020-0077), either `mapr` or `memmap2` might be good replacements.

**Comment by brightly-salty** [comment]
@vberger I can open a PR for this if it would be accepted. Looks like memmap2 is largely a drop-in replacement for memmap at the moment.

**Comment by vberger** [comment]
That sounds good then, thanks!
