### ISSUE TITLE
Crash when loading fontconfig

### ISSUE THREAD

**Issue by chrisduerr** [Smithay/client-toolkit#167]
This has been reported to Alacritty in https://github.com/alacritty/alacritty/issues/4591.

Generally the fontconfig of sctk should probably be reworked, but even if it doesn't it should under no circumstances just prevent the entire application from working. An unwrap in sctk on something that can actually occur seems rather inappropriate.

**Comment by vberger** [comment]
Indeed, this whole block should be formulated in a more error-tolerant way:

https://github.com/Smithay/client-toolkit/blob/f038eab8197019d530adc45d7a30e692c62b8e9b/src/window/concept_frame.rs#L642-L648

Probably the behavior should be to just log a warning when failing to load fontconfig, and just don't display any text.

**Comment by brightly-salty** [comment]
I'd be willing to attempt to implement this and submit a PR if it would be accepted.

**Comment by vberger** [comment]
@brightly-salty Thanks for offering your help, such a PR would be welcome ! :)
