### ISSUE TITLE
Touch input

### ISSUE THREAD

**Issue by l4l** [Smithay/client-toolkit#169]
If I understood correctly, now it's only possible to check whether seat has touch support or not, without any interface for handling input. It would be nice to support it.

Weston client as a usage example: https://github.com/wayland-project/weston/blob/master/clients/simple-touch.c

Protocol [retrieving an ojbect](https://github.com/wayland-project/wayland/blob/master/protocol/wayland.xml#L1819-L1831) and its [interface](https://github.com/wayland-project/wayland/blob/master/protocol/wayland.xml#L2304-L2446) (anything else missed?).

**Comment by vberger** [comment]
The big question here is: what can SCTK offer to improve [the bindings offered by `wayland-client` already](https://docs.rs/wayland-client/0.28.2/wayland_client/protocol/wl_seat/struct.WlSeat.html#method.get_touch).

For the handling of keyboard events, SCTK adds the logic to handle keymap translation. For pointers, SCTK adds the handling of cursor icons, and the associated logic.

Do you feel that there is something that SCTK could provide regarding touch events?

**Comment by l4l** [comment]
Oh, I haven't noticed this one in wayland-client, always forgot that docsrs doesn't search items in re-exports. I doesn't know much about the API itself, therefore I have no idea what kind of abstraction might be useful for end-users. As for me, wayland-client API looks sufficient.
