### ISSUE TITLE
Center window title based on whole window width

### ISSUE THREAD

**Issue by JMS55** [Smithay/client-toolkit#179]
Currently the window title seems to center on the remaining space left after the window control buttons are taken into account. I feel that it would look better centering solely based off the window width.

**Comment by vberger** [comment]
I have decided in #183 that SCTK should only provide a minimalist `FallbackFrame` that does not draw any title, as font loading & rendering is too much of a task to get right in SCTK. I invite you to create your own implementation of the `Frame` trait to create decorations fitting your needs.
