### ISSUE TITLE
Shared memory anonymous files location

### ISSUE THREAD

**Issue by emersion** [Smithay/client-toolkit#18]
I noticed the `wl_shm` helper uses a regular temporary directory to create an in-memory file. This should probably be replaced with `XDG_RUNTIME_DIR` as creating a file for `wl_shm` backed by a disk should really be avoided.

Also, it's possible to create the file, open it, and immediately unlink it to make sure we're not leaking it.

Bonus point: some systems support better ways to allocate an anonymous file (see https://github.com/myfreeweb/shmemfdrs). Some systems also support file sealing which can ensure the file won't shrink (shrinking a file can cause SIGBUS on the compositor side, it's currently mitigated with a signal handler but it's a pretty hacky solution).

**Comment by vberger** [comment]
Hmm, for some reason I was persuaded that the `tempfile` crate created temporary files that were not actually linked to the disk. Rereading its documentation, it's actually not clear at all that this would be the case. Thanks for noticing this.

**Comment by trimental** [comment]
I'm just wondering whether this is a discussion about the location of the memory files or a discussion on passing an anonymous file descriptor like [memfd](http://man7.org/linux/man-pages/man2/memfd_create.2.html), or both?

**Comment by emersion** [comment]
The high priority issue is the temporary files location. Using `memfd` and sealing would be nice to have, but it's more in the wishlist than high priority IMHO.

**Comment by vberger** [comment]
Actually @emersion 

> Also, it's possible to create the file, open it, and immediately unlink it to make sure we're not leaking it.

Isn't that what the `tempfile` file is actually doing already? see https://github.com/Stebalien/tempfile/blob/master/src/file/imp/unix.rs#L66-L72

**Comment by emersion** [comment]
Oh right. It even uses `O_TMPFILE` instead when available (https://github.com/Stebalien/tempfile/blob/master/src/file/imp/unix.rs#L75).

**Comment by vberger** [comment]
Done in #26
