### ISSUE TITLE
SimpleGlobal shouldn't blindly bind the latest version of the interface

### ISSUE THREAD

**Issue by tadeokondrak** [Smithay/client-toolkit#186]
Changes to Wayland interfaces aren't forward compatible, and there have been multiple cases of a Wayland protocol changing behaviour between versions (grep SINCE_VERSION in wlroots for examples.)

`SimpleGlobal` doesn't provide a way to limit what version it binds, so clients can break when the compositor upgrades a protocol. It should probably have a "maximum version" parameter at least, or maybe a version range.

**Comment by danieldg** [comment]
Note: the Interface traits already have a VERSION associated const corresponding to the protocol version they were compiled from.  This should also be used as a maximum - so clients *may* request a lower version than VERSION, but it should be an error to request a higher one, and the actual version used should be min(server's version, protocol XML version, client's requested version).
