### ISSUE TITLE
`blocking_dispatch` does not flush messages

### ISSUE THREAD

**Issue by yilinwei** [Smithay/client-toolkit#297]
Hi,

I was trying out the `wgpu` example, which blocks indefinitely on `sway` version `1.7` during the initial global registration.

https://github.com/Smithay/client-toolkit/blob/87424f2cd10d50422d81ee0444e92becb45d43c4/examples/wgpu.rs#L51

When running with `WAYLAND_DEBUG=1` I only get the first two messages logged and then none of the expected messages from the server.

```
[ 624925.960]  -> wl_display@1.get_registry(new id wl_registry@2)
[ 624925.999]  -> wl_display@1.sync(new id wl_callback@3)
```

Calling `flush` directly with the snippet works as expected.

```rust
    event_queue.dispatch_pending(&mut wgpu).unwrap();
    event_queue.flush().unwrap();
```

**Comment by i509VCB** [comment]
Hi, this behavior is actually the result of a bug in wayland-rs fixed on this commit: https://github.com/Smithay/wayland-rs/commit/60f6aaa0c8c178b9a76a7677f487ab145a44017b

Currently there are some pull requests we are working on, but we could ask if @vberger could do a release to fix this bug until the open pull requests are done

**Comment by yilinwei** [comment]
Ah! I should have checked the issues in the other repo.

No worries, I can code around this issue since I control the loop anyway.

Feel free to close the issue as a duplicate.

**Comment by ids1024** [comment]
This is fixed with https://github.com/Smithay/client-toolkit/pull/300 and can be closed now, I believe?
