### ISSUE TITLE
[Question] Using `Queue` / `EventLoop` with requests properly

### ISSUE THREAD

**Issue by JakeStanger** [Smithay/client-toolkit#308]
Hey, I'm using the client toolkit for my project and have managed to hook up the [wlr-foreign-toplevel-management-unstable-v1](https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/blob/master/unstable/wlr-foreign-toplevel-management-unstable-v1.xml) protocol. 

I'm receiving events from the manager successfully using the `calloop::EventLoop`:

```rs
let mut event_loop = calloop::EventLoop::<()>::try_new().unwrap();
WaylandSource::new(queue)
    .quick_insert(event_loop.handle())
    .unwrap();

loop {
    event_loop.dispatch(None, &mut ()).unwrap();
}
```

Elsewhere I'm trying to send a request using [wlr_foreign_toplevel_handle_v1::activate](https://wayland.app/protocols/wlr-foreign-toplevel-management-unstable-v1#zwlr_foreign_toplevel_handle_v1:request:activate) where I'm encountering an issue - the nature of the event loop means it waits for events before sending requests, so the `activate` request doesn't actually go through until the manager receives a different event. I can get round this by sticking a short timeout (50ms) on the loop.

My question is this: is the timeout the correct approach to go about this, or is there some mechanism I'm missing with Wayland or `calloop` which I can call after `activate()` that'll force-process requests?

**Comment by i509VCB** [comment]
If you send the request inside the Dispatch handlers, it should be flushed automatically. If you do it from a timer or via dbus you will need to flush the connection.

Also make sure you are using wayland-client beta 10, there was a bug in beta 9

**Comment by JakeStanger** [comment]
Thanks for the reply. It sounds like my usecase calls for a full flush, in which case I think I need to be calling `sync_roundtrip` on the queue?

**Comment by i509VCB** [comment]
sync_roundtrip could work, just note that the queue will block until that message is received.

**Comment by i509VCB** [comment]
If you have any further questions, feel free to open a new issue or comment here.
