### ISSUE TITLE
Server-side decorations

### ISSUE THREAD

**Issue by Laaas** [Smithay/client-toolkit#31]
Will smithay-client-toolkit support server-side decorations?

**Comment by trimental** [comment]
It does, it was implemented in https://github.com/Smithay/client-toolkit/pull/20 but some compositors, such as [mutter](https://gitlab.gnome.org/GNOME/mutter/issues/217) on gnome, have chosen not to or just haven't yet implemented server side decorations.

**Comment by Laaas** [comment]
Ah I thought it didn't since I couldn't find anything mentioning it! My fault. Thanks!
