### ISSUE TITLE
RUSTSEC-2022-0048: xml-rs is unmaintained

### ISSUE THREAD

**Issue by uncomfyhalomacro** [Smithay/client-toolkit#315]
Relevant link: https://rustsec.org/advisories/RUSTSEC-2022-0048

Possible alternative: https://crates.io/crates/quick-xml

**Comment by i509VCB** [comment]
The current master branch uses the 0.30 wayland-rs beta versions which both no longer use xml-rs (instead using quick-xml). This crate is however not ready to release a new version yet.

**Comment by uncomfyhalomacro** [comment]
oh. alright thanks for letting me know. i submitted this issue because iced-rs may be using the version containing xml-rs. i should probably wait til this crate publishes a new release
