### ISSUE TITLE
WGPU example crashes with zwp_linux_dmabuf_v1 error

### ISSUE THREAD

**Issue by aakamenov** [Smithay/client-toolkit#367]
I tried running the WGPU example on the latest `master` commit ab15882 (after fixing the compile errors, I see there's already a PR addressing this) and got the following error: `wl_display@1: error 1: invalid arguments for zwp_linux_dmabuf_v1@12.get_surface_feedback` with a panic: ```thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', github.com-1ecc6299db9ec823/khronos-egl-4.1.0/src/lib.rs:1542:42```.
Wayland debug output: [debug.txt](https://github.com/Smithay/client-toolkit/files/10961768/debug.txt)

Should mention that I had to change `wgpu::PresentMode::Mailbox` to `wgpu::PresentMode::Fifo` as the former is not supported for me.

I tried getting an OpenGL renderer going with `glutin` and `femtovg` and got the exact same error. The other examples are running fine though.

Running on AMD Radeon Vega 8 integrated graphics and Hyprland.

**Comment by i509VCB** [comment]
This is almost certainly going to be a driver issue. Are you using the Mesa userspace drivers (radv, radeonsi) or the proprietary userspace (amdvlk)?

> Should mention that I had to change wgpu::PresentMode::Mailbox to wgpu::PresentMode::Fifo as the former is not supported for me.

Could wgpu be falling back to the EGL platform where it can't figure out what presentation mode is actually being used?

**Comment by aakamenov** [comment]
I'm running the open-source Mesa drivers. Do I have to switch to the proprietary driver instead?

> Could wgpu be falling back to the EGL platform where it can't figure out what presentation mode is actually being used?

I suppose so, at least judging by where the panic occurs in both the WGPU and my OpenGL examples. Actually, with `glutin` the only option is to use EGL (and GLX which is for X11). In the WGPU example, trying to set `wgpu::Backends::VULKAN` or `wgpu::Backends::PRIMARY` fails when trying to select an adapter here: https://github.com/Smithay/client-toolkit/blob/fa73882153610a9526baca8050876d287d4e37f5/examples/wgpu.rs#L91

**Comment by aakamenov** [comment]
So I had to install Radeon's Vulkan Mesa driver. On Arch this is: https://archlinux.org/packages/extra/x86_64/vulkan-radeon
