### ISSUE TITLE
Key repetition sometimes get stuck

### ISSUE THREAD

**Issue by vberger** [Smithay/client-toolkit#37]
In alacritty, sometimes when gaining back focus after it being lost (because I started a program), the key repetition of `<enter>` is triggered even though the key on my keyboard is not.

I think this is because alacritty lost the focus while the `<enter>` key was pressed, and for some reason the repetition triggered again when the focus was re-gained. This is very likely a bug in sctk.

**Comment by trimental** [comment]
This might be fixed with https://github.com/Smithay/client-toolkit/pull/32. Did you try with the latest client toolkit master?

**Comment by vberger** [comment]
Ah, this has not been released yet, right.
