### ISSUE TITLE
Cannot find xbcommon

### ISSUE THREAD

**Issue by Horus645** [Smithay/client-toolkit#370]
Hello, I am currently building a wallpaper daemon on top of sctk.

Some users have reported they cannot build the application, because sctk fails to find `xbcommon`, despite it being installed.

See [here](https://github.com/Horus645/swww/issues/99) for details (I unfortunately couldn't reproduce it myself, but since 2 users have reported it, I assume it is not a one off thing).

I'd like to add that keyboard support is absolutely useless for me (in this particular case), so adding a feature to allow me to disable keyboard handling support would be enough to fix this. I suppose I could instead use the raw wayland_protocol and wayland_client crates, but then I lose the benefits of sctk's ease of use.

**Comment by wash2** [comment]
Hi, your users may have libxkbcommon, but be missing `libxkbcommon-dev` or a non-ubuntu / debian equivalent. Maybe they can try installing it and trying the build again.

**Comment by wash2** [comment]
You could also probably just not use the xkbcommon feature.

**Comment by Horus645** [comment]
> You could also probably just not use the xkbcommon feature.

Is this possible on `0.16`? Because I am already setting `default-features=false` and only enabling `calloop`.

**Comment by wash2** [comment]
> Is this possible on 0.16? Because I am already setting default-features=false and only enabling calloop.

Ahh, no probably not on 0.16

**Comment by Horus645** [comment]
Hi again, with 0.17 I can already disable the `xkbcommon` feature, so I will be closing this issue. Thanks!
