### ISSUE TITLE
[Question] How to use webgpu with layer shell

### ISSUE THREAD

**Issue by Arjun31415** [Smithay/client-toolkit#391]
Thank you for this amazing project. I  am currently stuck on rendering layer using wgpu .

https://github.com/Smithay/client-toolkit/blob/ee7dc784f41d6c519756976c0f37ffec16218983/examples/simple_layer.rs#L48
What changes should I make to use gpu in here.
 
I am referring the next wgpu example, but that is with windows and requires some window handles.
The parameters to this function require raw window handle 
https://github.com/Smithay/client-toolkit/blob/ee7dc784f41d6c519756976c0f37ffec16218983/examples/wgpu.rs#L85

Could you please guide.

**Comment by wash2** [comment]
Hi, the creation of the handle should be very similar, except using the wl_surface of the layer shell surface instead of the the window. https://github.com/Smithay/client-toolkit/blob/ee7dc784f41d6c519756976c0f37ffec16218983/examples/wgpu.rs#L55

**Comment by Arjun31415** [comment]
Referring this [doc](https://docs.rs/smithay-client-toolkit/latest/smithay_client_toolkit/shell/wlr_layer/struct.LayerShell.html) I can only see [create_layer_surface](https://docs.rs/smithay-client-toolkit/latest/smithay_client_toolkit/shell/wlr_layer/struct.LayerShell.html#method.create_layer_surface) method on layer shell. If I try to use the compositor to make the surface, it (as expected) gives 

```
the trait `From<wgpu::Surface>` is not implemented for `smithay_client_toolkit::compositor::Surface
```

How do I create it from the layer shell.
 
The (incorrect) code -
```rs
    env_logger::init();

    // All Wayland apps start by connecting the compositor (server).
    let conn = Connection::connect_to_env().unwrap();

    // Enumerate the list of globals to get the protocols the server implements.
    let (globals, mut event_queue) = registry_queue_init(&conn).unwrap();
    let qh = event_queue.handle();

    // The compositor (not to be confused with the server which is commonly called the compositor) allows
    // configuring surfaces to be presented.
    let compositor = CompositorState::bind(&globals, &qh).expect("wl_compositor is not available");
    let surface = compositor.create_surface(&qh);
    // This app uses the wlr layer shell, which may not be available with every compositor.
    let layer_shell = LayerShell::bind(&globals, &qh).expect("layer shell is not available");
    // Initialize wgpu
    let instance = wgpu::Instance::new(wgpu::InstanceDescriptor {
        backends: wgpu::Backends::all(),
        ..Default::default()
    });
    // Create the raw window handle for the surface.
    let handle = {
        let mut handle = WaylandDisplayHandle::empty();
        handle.display = conn.backend().display_ptr() as *mut _;
        let display_handle = RawDisplayHandle::Wayland(handle);

        let mut handle = WaylandWindowHandle::empty();

       // Need to create surface here 
        handle.surface = surface as *mut _;
        let window_handle = RawWindowHandle::Wayland(handle);

        /// https://github.com/rust-windowing/raw-window-handle/issues/49
        struct YesRawWindowHandleImplementingHasRawWindowHandleIsUnsound(
            RawDisplayHandle,
            RawWindowHandle,
        );

        unsafe impl HasRawDisplayHandle for YesRawWindowHandleImplementingHasRawWindowHandleIsUnsound {
            fn raw_display_handle(&self) -> RawDisplayHandle {
                self.0
            }
        }

        unsafe impl HasRawWindowHandle for YesRawWindowHandleImplementingHasRawWindowHandleIsUnsound {
            fn raw_window_handle(&self) -> RawWindowHandle {
                self.1
            }
        }

        YesRawWindowHandleImplementingHasRawWindowHandleIsUnsound(display_handle, window_handle)
    };
    // A layer surface is created from a surface.
    let surface = unsafe { instance.create_surface(&handle).unwrap() };
```

**Comment by Arjun31415** [comment]
My code has the layer surface initialization, but I did it after handle which was wrong, and as you pointed out by using WaylandSurface I was able to render using wgpu.

Thank you for your time.
