### ISSUE TITLE
`calloop` dependency out of date

### ISSUE THREAD

**Issue by OvermindDL1** [Smithay/client-toolkit#402]
`calloop` is up to 0.11 now, which includes an updated nix dependency as well, any chance this could be updated in a release?

**Comment by wash2** [comment]
Sure, I'll see if I can update it for the next release.

**Comment by kchibisov** [comment]
calloop will be updated, once the github.com/smithay/calloop-wayland-source will have an update, which waits for a new calloop breaking version, which should be soon due to https://github.com/Smithay/calloop/pull/144 .
