### ISSUE TITLE
scale_factor_changed doesn't seem to be called on v0.18.0

### ISSUE THREAD

**Issue by aakamenov** [Smithay/client-toolkit#423]
On v0.18.0 the `scale_factor_changed` method on `CompositorHandler` is not being called anymore when the program initially runs whereas it used to be on v0.17.0. I tried to log the `new_factor` value in the simple_layer and simple_window examples on both the new and the older versions and it only ever prints it on the older one. Is this intended behaviour or a regression?

I'm running Hyprland v0.30.0

**Comment by kchibisov** [comment]
provide a `WAYLAND_DEBUG=1` log for that.

**Comment by aakamenov** [comment]
Attaching the logs from running the simple_layer example on both v0.18.0 and v0.17.0.
[v0_17_0.log](https://github.com/Smithay/client-toolkit/files/13063347/v0_17_0.log)
[v0_18_0.log](https://github.com/Smithay/client-toolkit/files/13063349/v0_18_0.log)

**Comment by kchibisov** [comment]
From the logs:

```
[1697978646.264171] <- wl_registry@2.global, (4, Some("wl_compositor"), 6)
[1697978646.266352] -> wl_registry@2.bind (4, Some("wl_compositor"), 6, wl_compositor@3)
```

Your compositor advertises support for `wl_compositor v6` however it doesn't configure any scaling, so bug your compositor to behave or not advertise the protocols it doesn't support. SCTK uses v6 scaling and not output scaling. Your compositor must send `wl_compositor::preferred_buffer_scale` when clients are using `v6`.

**Comment by kchibisov** [comment]
https://github.com/hyprwm/Hyprland/issues/3635

**Comment by aakamenov** [comment]
I see, Hyprland issue then. Was going to post an issue there but you beat me to it. Thanks for the help!
