### ISSUE TITLE
Received event for dead output

### ISSUE THREAD

**Issue by thvdveld** [Smithay/client-toolkit#458]
I'm using Alacritty with Hyprland. My setup is a laptop with an external screen. In my Hyprland config, I have the following line:
`
bindl = , switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1,disable"
`

This disables my laptop display when closing the lid. When I close my lid, all my alacritty instances panic with the following error message:
`thread 'main' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smithay-client-toolkit-0.18.1/src/output.rs:425:14:
Received event for dead output`

**Comment by kchibisov** [comment]
hyprland send event for a global that it deleted.

Please try different compositor and do the same thing, like sway.
