### ISSUE TITLE
Support loading dpi-scaled cursor images

### ISSUE THREAD

**Issue by vberger** [Smithay/client-toolkit#47]
The `ThemedPointer` should be improved to support dpi-scaled icons loading.

**Comment by kchibisov** [comment]
Do we want to add something like 
```rust
pub fn theme_pointer_with_dpi(&self, pointer: Proxy<wl_pointer::WlPointer>, dpi: u32) -> ThemedPointer
``` 
and new constructor for ThemeManager or to add just one dpi aware constructor for ThemeManager and create new pointers with this dpi auto applied?

**Comment by vberger** [comment]
I think the simplest & most consistent way would be to just have cursors always be dpi-aware, using the dpi-tracking facility already in SCTK.

Though, this is mostly adding more inter-coupling between the modules of SCTK. At this point I think this is illusory to maintain the very-loose coupling that is the current state...

**Comment by kchibisov** [comment]
Hm, just looking through the window code(basic_frame and concept_frame) it seems like they use AutoThemer, what's the use case of AutoThemer etc without Window(surface)?

**Comment by vberger** [comment]
AutoThemer provides the necessary tools to change the cursor image. The window code uses it to change the cursor for resizing interactions.

One thing to be aware of is that in Wayland, a surface and a window are two quite different things. A surface is just a canvas the client draws on, and for it to be displayed it must be assigned a role. The two most common roles are "toplevel" (aka: window), and "pointer", a cursor image.

So an app build using SCTK will actually manipulate several surfaces: the surface for its main content, the surface manager by the `AutoThemer` for cursor icons, and a few other surfaces used to draw the decorations by ConceptFrame.

Now, writing all that I realize that we actually cannot have the Themer track the DPI by itself, because it does not have access to a surface to track it. So I see two approaches:

- setup the Themer to monitor the list of outputs (using an handle to the `OutputMgr`), compute the highest dpi factor of all outputs, and always use this one. Meaning the compositor will have to downsample the cursor icon on the lower-dpi screens. Which would likely have a rather low cost in practice given they are small surfaces.
- add a `set_cursor_with_dpi(...)` method to `ThemedPointer`/`AutoPointer` allowing the user to specify the required dpi when changing the pointer. The user is now responsible for knowing which DPI factor it wants the cursor to be user with.

In the second case, `ThemeManager` would thus load the cursors themes lazily for any required dpi factor, and cache the dpi-instanciated themes for later use, it'd say.

**Comment by kchibisov** [comment]
As far as I can see, after a recent rework of SCTK there was an attempt to implement HiDPi cursors, however it turned out that they are still not working on default examples.
