### ISSUE TITLE
Cannot `set_title()` while handling window events

### ISSUE THREAD

**Issue by trimental** [Smithay/client-toolkit#56]
When using `set_title()` and also handling an event of the windows implementation a mutex deadlock occurs. 

`set_title()` triggers a `FrameRequest::Refresh` by locking the windows implementation. If the windows implementation is locked while inside the windows implementation then a deadlock occurs.

A small example being
```
match next_action.lock().unwrap().take() {
  Some(WEvent::Refresh) => {
    window.set_title("refreshed".into());
    window.refresh();
    window.surface().commit();
  }
}
```

**Comment by vberger** [comment]
Indeed, there is some inconsistency between some methods of window. Some require a refresh to be called afterwards, and some trigger a refresh event directly, I think we could harmonize all that.
