### ISSUE TITLE
Button (inactive) colors doesn't appear to do anything

### ISSUE THREAD

**Issue by JMurph2015** [Smithay/client-toolkit#67]
This is coming from from much higher in the stack, but in my testing on Alacritty, which uses this library via `winit`, changing the button color (other than the hovered color) doesn't seem to do anything.  Can anyone observe similar results?

**Comment by vberger** [comment]
This is actually a characteristic of the `ConceptFrame`, which does not color inactive buttons. If you check the `BasicFrame` for example, the inactive color is use when the buttons are not hovered.

**Comment by JMurph2015** [comment]
Changed in #68, buttons backgrounds are now shaded on `ConceptFrame`.
