### ISSUE TITLE
Decorations inconsistency

### ISSUE THREAD

**Issue by vberger** [Smithay/client-toolkit#70]
Currently SCTK will explicitly request SSD when creating a window, but call `unset_mode()` when the user calls `set_decorate(true)`, then following the compositor's preference.

This leads to inconsistencies when the compositor prefers CSD but honors SCTK's request for SSD at startup: if decorations are disabled then re-enabled, they will appear as CSD.

What should be do? Always prefer SSD or always follow the compositor preference?

**Comment by trimental** [comment]
Imo `init_from_env` should follow compositor preference however I think there should be a separate function for forcing SSD
