### ISSUE TITLE
On Weston, clicking the minimize button leaves the CSD on screen

### ISSUE THREAD

**Issue by YaLTeR** [Smithay/client-toolkit#79]
Its pixels disappear when moving the mouse across them, so it's probably a damage issue? Occurs on default examples, e.g. `themed_frame`, as well as `alacritty`.

**Comment by vberger** [comment]
Yeah, I've noticed this as well for some time, I have no idea if its a weston bug or an sctk bug though.

**Comment by YaLTeR** [comment]
@vberger has found that apparently a bug like this is reported to Weston: https://gitlab.freedesktop.org/wayland/weston/issues/96, so probably not a sctk issue.
