### ISSUE TITLE
Zero size windows

### ISSUE THREAD

**Issue by ColinKinloch** [Smithay/client-toolkit#8]
I've run into an issue when running some examples dependant on this create.

Windows are created with their decorations outside of the top and left bounds of the monitor.

When I try and resize the window it panics with `thread 'main' panicked at 'attempt to multiply with overflow', src/window/basic_frame.rs:380:27`
Gnome activities overview seems to indicate a window with no size.

In `src/window/mod.rs` on resize start the `Event::Configure` event has a `new_size` of `(1, 1)`
`frame.subtract_borders` returns negative numbers which wrap at the end of `new_size.map`.
Changing the return value to `(map(w, 1) as u32, max(h, 1) as u32)` fixes the panic.

It seems like it's not reporting the window size or the decorations to the shell.

It's using the xdg shell.
I've tried it with the client-toolkit selection and gfx quad examples.
Gnome 3.28.2

![Window](https://user-images.githubusercontent.com/334272/41913644-c9ad3b6a-7948-11e8-8a69-62c22e5f933d.png)
![Overview](https://user-images.githubusercontent.com/334272/41913651-cea572ae-7948-11e8-9a78-32e68cdfcdb6.png)

**Comment by vberger** [comment]
Good catch regarding the handling of negative values, I'll correct that.

However, regarding the location of the window, afaik the wayland compositor is supposed to infer the dimensions of the window from the contents of the surfaces, and for some reason it appears that Mutter only locates the window using the main surface, and not the subsurfaces used to draw the borders...

**Comment by vberger** [comment]
I have pushed some changes on master. Could you test them and tell me if/how it improves your issue?

**Comment by ColinKinloch** [comment]
Suddenly works perfectly, thanks a lot.

**Comment by vberger** [comment]
Good, I'll make a point release with that then.
