### ISSUE TITLE
Large maximum window size causes protocol error

### ISSUE THREAD

**Issue by yvt** [Smithay/client-toolkit#82]
I noticed that when a very large window size (around `u32::max_value()`) is specified via `set_max_size`, it causes a protocol error with the following error message:

```
xdg_toplevel@31: error 4: invalid negative max size requested -256 x -226
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 71, kind: Other, message: "Protocol error" }', src/libcore/result.rs:1084:5
...
```
There are two potential sources of integer overflow that cause this problem. The first one is conversion from `u32` to `i32`:
https://github.com/Smithay/client-toolkit/blob/1d8fa7acac75618fe1ef5db677bb90fe66f3a406/src/window/mod.rs#L560-L567
The second one is here:
https://github.com/Smithay/client-toolkit/blob/1d8fa7acac75618fe1ef5db677bb90fe66f3a406/src/window/concept_frame.rs#L715-L721

Would it be a good idea to use saturating arithmetic in these places to prevent them from wrapping around to negative values?

**Comment by vberger** [comment]
Overflowing an `i32` here means we are considering window dimensions of more than 2 billion pixels wide or high...

To be quite honest I'm not sure there is any realistic case where this could happen, and so if there is any reason to try and support that at all.

**Comment by yvt** [comment]
A large value passed to `set_max_size` could stand in for infinity, meaning the window size is unrestricted in a particular direction. Applications and GUI toolkits could use it during layouting because it's often simpler than using `Option`. But the more important use case is when you want to restrict a window size only for one axis, leaving the other axis unbounded. This is currently impossible to do without using a stand-in infinite value because `set_max_size` requires both axes to be either bounded or unbounded and does not accept any other combinations.

It's realistic to specify an unrealistic value as a maximum size because the natural interpretation of it is that it only makes the intrinsic maximum size smaller, and doesn't make a size which wasn't acceptable acceptable. Thus, if a maximum size is excessively large, it should be treated as if not having a maximum size at all. If some range of maximum sizes isn't accepted and breaks things, it should be explicitly documented.

**Comment by vberger** [comment]
Oh, ok, I see. In that case it is more an issue of API design & documentation.

The actual correct way to represent an unlimited maximum size for a given axis in the Wayland protocol is to give a max size of 0 for this axis. I attempted with `Option<_>` to make it more intuitive, but it indeed fails to cover the case where one only wants to limit a single axis.

With that added to the fact that the only valid values for these numbers are positive i32 (I still don't understand why they chose to use i32 type for these fields while also specifying that negative values are forbidden).
