### ISSUE TITLE
Default to XCursor theme/size from env

### ISSUE THREAD

**Issue by emersion** [Smithay/client-toolkit#86]
When the application doesn't specify an XCursor theme/size, read it from `XCURSOR_THEME` and `XCURSOR_SIZE`. This allows the compositor to have primitive control over these settings.

This is already done by various X11 clients, Qt, Weston clients, mpv, glfw, etc.

**Comment by vberger** [comment]
Done in https://github.com/Smithay/client-toolkit/commit/4efbcf51a8126578035e9e2e0c238d268538a9fd
