### ISSUE TITLE
clicks in themed window titlebar swallowed in recent Fedora 31 update

### ISSUE THREAD

**Issue by wez** [Smithay/client-toolkit#92]
Running mutter-3.34.3-2.fc31.x86_64 (and/or whatever the default wayland/gnome 3 environment is on Fedora); you can repro this with:

```
cargo run --release --example themed_frame
```

clicks in the titlebar go through to whatever is behind the window.

I'm using client-toolkit 0.6 in my real app, but the same issue can be reproduced with master.

I suspect that `mutter` likely recently changed its behavior as I only started to hit this today after a reboot, although it has been bothering a friend that reported it in https://github.com/wez/wezterm/issues/139 for about a week.

**Comment by YaLTeR** [comment]
There's this GNOME issue: https://gitlab.gnome.org/GNOME/mutter/issues/1024

**Comment by kchibisov** [comment]
This bug should be fixed with gnome-shell v3.34.4, so there's no need to keep this issue around anymore . https://gitlab.gnome.org/GNOME/mutter/merge_requests/1040

**Comment by wez** [comment]
Yep, confirmed fixed.
