### ISSUE TITLE
Expand Theme to include additional theme parameters

### ISSUE THREAD

**Issue by digitalstreamio** [Smithay/client-toolkit#98]
With the 0.7 version, we get more flexibility to style CSD decorations. This is great.
There are still a few more parameters that would be useful in order to implement more refined CSD.

[colors]

1.  button idle color when window is inactive - frequently inactive windows change button background in addition to header background.  

[visibility]

2. min/max button visibility - need to be able to turn them on/off if we want more minimalist header. 

[sizes]

3. button padding - height is already controlled by header size so that's fine, but it would be nice if we could specify start/end padding so that button aren't so narrow. 

4. font_size - being able to specify font size that ultimately controls header size would be nice too. 

Thanks!

**Comment by vberger** [comment]
I'm starting to think that `Theme` should rather be a `Config` associated type of `Frame`, rather than a generic trait.

This way, every implementation of `Frame` would be able to provide its own configuration options, rather than trying to push the entire universe of possible config options into a single generic trait.

**Comment by digitalstreamio** [comment]
For what its worth, I was able to work around item #1 by using alpha transparency for button color so that one could go away.

font_size or header height setting would be nice though as currently the header bar is a bit narrow compared to other apps (even those with custom CSD like Firefox or VSCode).

I do feel that ppl will keep asking you for more so an approach that provides more flexibility would certainly be interesting.

**Comment by vberger** [comment]
Most of these configuration options are now on master, with the exception of anything controlling the size of the decorations and buttons.

> it would be nice if we could specify start/end padding so that button aren't so narrow.

Do you mean to control the space between the buttons, or the width of the buttons?

> font_size - being able to specify font size that ultimately controls header size would be nice too.

I'd honestly prefer to have both configured independently, to keep the implementation reasonably simple.

**Comment by vberger** [comment]
Following #183, the decorations provided in SCTK are explicitly FallbackFrame, a minimalist set of decorations that ensure usability of the window but makes no attempt at particular visual quality. Users of SCTK are invited to create their own implementation of the Frame trait fitting their needs.
